VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IDocumentService"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database

Public Function GenerarDocumento(ByVal SolicitudID As Long) As String
End Function

Public Function LeerDocumento(ByVal rutaDocumento As String) As ESolicitud
End Function
