VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IMapeoRepository"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database

Public Function GetMapeoPorTipo(ByVal tipoSolicitud As String) As EMapeo
End Function

Public Function ObtenerMapeosPorCategoria(ByVal categoria As String) As Object
End Function
